youwe_media:
    resource: "@YouweMediaBundle/Controller/"
    type:     annotation
    prefix:   /media

youwe_uploads:
    pattern: /uploads/{name}
    requirements:
        name: .+
    defaults:
        _controller: YouweMediaBundle:Uploads:uploads